[HOPSWORKS-2195] Attach Jupyter configuration to notebook as Xattr
logicalclocks/sparkmagic pull request #14
Opened 2020-12-19 00:52 UTC by gibchikafa

2020-12-29 10:37 UTC, tkakantousis commented on sparkmagic/sparkmagic/livyclientlib/livysession.py
> +        print(jwt_text)
```suggestion
```

2021-01-04 15:18 UTC, robzor92 requested changes

2021-01-04 15:18 UTC, robzor92 commented on sparkmagic/sparkmagic/livyclientlib/livysession.py
> +        self.ipython_display.writeln(resource_url)
Do we need to print this in the notebook?

2021-01-04 15:18 UTC, robzor92 commented on sparkmagic/sparkmagic/livyclientlib/livysession.py
> +        self.ipython_display.writeln("Repeat" + resource_url)
And print this?

2021-01-04 15:28 UTC, gibchikafa commented on sparkmagic/sparkmagic/livyclientlib/livysession.py
> +        self.ipython_display.writeln("Repeat" + resource_url)
It was for debugging. I will remove it.

2021-02-12 16:39 UTC, robzor92 approved these changes

2021-03-03 14:18 UTC, merged